# Site settings
title:          Hidrokit Blog
description:    "Berita baru mengenai hidrokit"
baseurl: "/blog"
url: "https://hidrokit.github.io"

# Theme settings
theme:          tale
# remote_theme: chesterhow/tale

# Build settings
markdown:       kramdown
include:
  - _pages

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Excludes
exclude: [ Gemfile, Gemfile.lock ]
