# Site settings
title:          Hidrokit Blog
description:    "Berita baru mengenai hidrokit"
baseurl:        ""
url:            ""

# Theme settings
theme:          tale
# remote_theme: cheseterhow/tale

# Build settings
markdown:       kramdown
include:
  - _pages

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
